# Generated by Django 3.0.8 on 2021-11-22 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20210606_0651'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('rock', 'Rock'), ('pop', 'Pop'), ('new-age', 'New Age')], max_length=256)),
            ],
        ),
        migrations.AlterField(
            model_name='track',
            name='tags',
            field=models.ManyToManyField(blank=True, to='backend.Tag'),
        ),
        migrations.AddField(
            model_name='track',
            name='tags2',
            field=models.ManyToManyField(blank=True, to='backend.Tag2', verbose_name='tags w/choices'),
        ),
    ]
