from django.conf import settings

MAX_COLUMNS = getattr(settings, 'AJAX_DATATABLE_MAX_COLUMNS', 30)
TRACE_COLUMNDEFS = getattr(settings, 'AJAX_DATATABLE_TRACE_COLUMNDEFS', False)
TRACE_QUERYDICT = getattr(settings, 'AJAX_DATATABLE_TRACE_QUERYDICT', False)
TRACE_QUERYSET = getattr(settings, 'AJAX_DATATABLE_TRACE_QUERYSET', False)
TEST_FILTERS = getattr(settings, 'AJAX_DATATABLE_TEST_FILTERS', False)
DISABLE_QUERYSET_OPTIMIZATION = getattr(settings, 'AJAX_DATATABLE_DISABLE_QUERYSET_OPTIMIZATION', False)
STRIP_HTML_TAGS = getattr(settings, 'AJAX_DATATABLE_STRIP_HTML_TAGS', True)
