from django.conf import settings

MAX_COLUMNS = getattr(settings, 'AJAX_DATATABLE_MAX_COLUMNS', 30)
ENABLE_QUERYDICT_TRACING = getattr(settings, 'AJAX_DATATABLE_ENABLE_QUERYDICT_TRACING', False)
ENABLE_QUERYSET_TRACING = getattr(settings, 'AJAX_DATATABLE_ENABLE_QUERYSET_TRACING', False)
TEST_FILTERS = getattr(settings, 'AJAX_DATATABLE_TEST_FILTERS', False)
DISABLE_QUERYSET_OPTIMIZATION = getattr(settings, 'AJAX_DATATABLE_DISABLE_QUERYSET_OPTIMIZATION', False)
